### ISSUE TITLE
Error Exit in microbecensus  

### ISSUE THREAD

**Issue by amorendt** [sharpton/shotmap#7]
Hi,  I recently installed shotmap for one of our users, and when working with them to run an analysis we are getting the output below. Not sure of source of problem, and so far looking through the documentation and the scripts is not getting me anywhere in determining reason for the error exit, so I thought I would send this message looking for assistance. Please let me know if there is any additional information that I can provide. Thanks in advance,  Anita Orendt, CHPC, University of Utah

]$ more slurm-1153141.err-kp163
>> ARGUMENTS TO shotmap.pl: perl shotmap.pl -i /scratch/general/lustre/u0028729/1153141 -d /scratch/general/lustre/u0028729/shotmap_db --nproc=20
####################################################################
# Initializing the shotmap pipeline (Wed Apr 27 22:21:44 MDT 2016) #
####################################################################
[WARNING]: I don't see a previously created ffdb at /scratch/general/lustre/u0028729/1153141/shotmap_ffdb/ so I will try to create
 it.
[NOTE]: Starting a classification run using the following settings:
[NOTE]:    * Database name: <>
##################################################
# LOADING PROJECT (Wed Apr 27 22:21:44 MDT 2016) #
##################################################
[NOTE]: Initialized a parameters xml file here: /scratch/general/lustre/u0028729/1153141/shotmap_ffdb//parameters/parameters.xml
[NOTE]: Processing 1 sample associated with project 1153141 
[NOTE]: Successfully loaded 1 sample associated with the project 1153141 
####################################################
# TRANSLATING READS (Wed Apr 27 22:30:17 MDT 2016) #
####################################################
[NOTE]: Translating reads for sample ID n_albigula_foregut_all
	Waiting for all local jobs to finish...
	...metatrans (prodigal) has finished. Proceeding
#######################################################
# RUNNING LOCAL SEARCH (Wed Apr 27 22:36:52 MDT 2016) #
#######################################################
[NOTE]: Running search for sample ID n_albigula_foregut_all
	Waiting for local jobs to finish...
	...rapsearch finished. Proceeding
#########################################################
# PARSING SEARCH RESULTS (Thu Apr 28 05:35:34 MDT 2016) #
#########################################################
[NOTE]: Parsing results for sample n_albigula_foregut_all
	Waiting for local jobs to finish...
	...search results are parsed. Proceeding.
####################################################
# CLASSIFYING READS (Thu Apr 28 05:52:11 MDT 2016) #
####################################################
[NOTE]: Classification_id: 1
[NOTE]: Classifying reads from flatfile for sample ID n_albigula_foregut_all
	...classification complete. Classification map located here: /scratch/general/lustre/u0028729/1153141/shotmap_ffdb/output/Classifica
tion_Maps/ClassificationMap_Sample_n_albigula_foregut_all.tab
#################################################################
# ESTIMATING AVERAGE GENOME SIZE (Thu Apr 28 05:54:03 MDT 2016) #
#################################################################
Waiting for microbecensus to finish...
"run_microbe_census.py -t 8 /scratch/general/lustre/u0028729/1153141/shotmap_ffdb/n_albigula_foregut_all/ags/microbecensus/_mc.tmp.gz /scrat
ch/general/lustre/u0028729/1153141/shotmap_ffdb/n_albigula_foregut_all/ags/microbecensus/n_albigula_foregut_all_ags.mc > /scratch/general/lu
stre/u0028729/1153141/shotmap_ffdb/logs/microbecensus/microbecensus_n_albigula_foregut_all.log 2>&1" unexpectedly returned exit value 1 at /
uufs/chpc.utah.edu/sys/installdir/shotmap/1.0/lib/Shotmap/Run.pm line 3993.
 at /uufs/chpc.utah.edu/sys/installdir/shotmap/1.0/scripts/shotmap.pl line 24.
	main::__ANON__("\"run_microbe_census.py -t 8 /scratch/general/lustre/u0028729/"...) called at /uufs/chpc.utah.edu/sys/installdir/sho
tmap/1.0/ext/lib/perl5/Carp.pm line 167
	Carp::croak("\"run_microbe_census.py -t 8 /scratch/general/lustre/u0028729/"...) called at /uufs/chpc.utah.edu/sys/installdir/shotma
p/1.0/ext/lib/perl5/IPC/System/Simple.pm line 566
	IPC::System::Simple::_check_exit("run_microbe_census.py -t 8 /scratch/general/lustre/u0028729/1"..., 1, ARRAY(0x54e74d8)) called at 
/uufs/chpc.utah.edu/sys/installdir/shotmap/1.0/ext/lib/perl5/IPC/System/Simple.pm line 538
	IPC::System::Simple::_process_child_error(256, "run_microbe_census.py -t 8 /scratch/general/lustre/u0028729/1"..., ARRAY(0x54e74d8))
 called at /uufs/chpc.utah.edu/sys/installdir/shotmap/1.0/ext/lib/perl5/IPC/System/Simple.pm line 238
	IPC::System::Simple::capture("run_microbe_census.py -t 8 /scratch/general/lustre/u0028729/1"...) called at /uufs/chpc.utah.edu/sys/i
nstalldir/shotmap/1.0/lib/Shotmap/Run.pm line 3993
	Shotmap::Run::run_microbecensus(Shotmap=HASH(0x11acf28), "/scratch/general/lustre/u0028729/1153141/shotmap_ffdb/n_albig"..., "/scrat
ch/general/lustre/u0028729/1153141/shotmap_ffdb/n_albig"..., "/scratch/general/lustre/u0028729/1153141/shotmap_ffdb/logs/mi"...) called at /
uufs/chpc.utah.edu/sys/installdir/shotmap/1.0/lib/Shotmap/Results.pm line 345
	Shotmap::Results::estimate_ags(Shotmap=HASH(0x11acf28)) called at /uufs/chpc.utah.edu/sys/installdir/shotmap/1.0/scripts/shotmap.pl 
line 77

**Comment by sharpton** [comment]
Thanks for this message. Can you please provide me with a copy of this file:

*/scratch/general/lustre/u0028729/1153141/shotmap_ffdb/logs/microbecensus/microbecensus_n_albigula_foregut_all.log
*

That will help me determine what went wrong at this step.

Thanks,
Tom

On Thu, Apr 28, 2016 at 10:55 AM, amorendt <notifications@github.com> wrote:

> Hi, I recently installed shotmap for one of our users, and when working
> with them to run an analysis we are getting the output below. Not sure of
> source of problem, and so far looking through the documentation and the
> scripts is not getting me anywhere in determining reason for the error
> exit, so I thought I would send this message looking for assistance. Please
> let me know if there is any additional information that I can provide.
> Thanks in advance, Anita Orendt, CHPC, University of Utah
>
> ]$ more slurm-1153141.err-kp163
>
> ARGUMENTS TO shotmap.pl: perl shotmap.pl -i
> /scratch/general/lustre/u0028729/1153141 -d
> /scratch/general/lustre/u0028729/shotmap_db --nproc=20
> ####################################################################
> Initializing the shotmap pipeline (Wed Apr 27 22:21:44 MDT 2016)
>
> ####################################################################
> [WARNING]: I don't see a previously created ffdb at
> /scratch/general/lustre/u0028729/1153141/shotmap_ffdb/ so I will try to
> create
> it.
> [NOTE]: Starting a classification run using the following settings:
> [NOTE]: * Database name: <>
> ##################################################
> LOADING PROJECT (Wed Apr 27 22:21:44 MDT 2016)
>
> ##################################################
> [NOTE]: Initialized a parameters xml file here:
> /scratch/general/lustre/u0028729/1153141/shotmap_ffdb//parameters/parameters.xml
> [NOTE]: Processing 1 sample associated with project 1153141
> [NOTE]: Successfully loaded 1 sample associated with the project 1153141
> ####################################################
> TRANSLATING READS (Wed Apr 27 22:30:17 MDT 2016)
>
> ####################################################
> [NOTE]: Translating reads for sample ID n_albigula_foregut_all
> Waiting for all local jobs to finish...
> ...metatrans (prodigal) has finished. Proceeding
> #######################################################
> RUNNING LOCAL SEARCH (Wed Apr 27 22:36:52 MDT 2016)
>
> #######################################################
> [NOTE]: Running search for sample ID n_albigula_foregut_all
> Waiting for local jobs to finish...
> ...rapsearch finished. Proceeding
> #########################################################
> PARSING SEARCH RESULTS (Thu Apr 28 05:35:34 MDT 2016)
>
> #########################################################
> [NOTE]: Parsing results for sample n_albigula_foregut_all
> Waiting for local jobs to finish...
> ...search results are parsed. Proceeding.
> ####################################################
> CLASSIFYING READS (Thu Apr 28 05:52:11 MDT 2016)
>
> ####################################################
> [NOTE]: Classification_id: 1
> [NOTE]: Classifying reads from flatfile for sample ID
> n_albigula_foregut_all
> ...classification complete. Classification map located here:
> /scratch/general/lustre/u0028729/1153141/shotmap_ffdb/output/Classifica
> tion_Maps/ClassificationMap_Sample_n_albigula_foregut_all.tab
> #################################################################
> ESTIMATING AVERAGE GENOME SIZE (Thu Apr 28 05:54:03 MDT 2016)
>
> #################################################################
> Waiting for microbecensus to finish...
> "run_microbe_census.py -t 8
> /scratch/general/lustre/u0028729/1153141/shotmap_ffdb/n_albigula_foregut_all/ags/microbecensus/
>
>
>
>
> *mc.tmp.gz /scrat
> ch/general/lustre/u0028729/1153141/shotmap_ffdb/n_albigula_foregut_all/ags/microbecensus/n_albigula_foregut_all_ags.mc
> <http://n_albigula_foregut_all_ags.mc> > /scratch/general/lu
> stre/u0028729/1153141/shotmap_ffdb/logs/microbecensus/microbecensus_n_albigula_foregut_all.log
> 2>&1" unexpectedly returned exit value 1 at /
> uufs/chpc.utah.edu/sys/installdir/shotmap/1.0/lib/Shotmap/Run.pm
> <http://chpc.utah.edu/sys/installdir/shotmap/1.0/lib/Shotmap/Run.pm> line
> 3993. at /uufs/chpc.utah.edu/sys/installdir/shotmap/1.0/scripts/shotmap.pl
> <http://chpc.utah.edu/sys/installdir/shotmap/1.0/scripts/shotmap.pl> line
> 24. main::__ANON_*("\"run_microbe_census.py -t 8
> /scratch/general/lustre/u0028729/"...) called at /uufs/
> chpc.utah.edu/sys/installdir/sho
> tmap/1.0/ext/lib/perl5/Carp.pm line 167
> Carp::croak("\"run_microbe_census.py -t 8
> /scratch/general/lustre/u0028729/"...) called at /uufs/
> chpc.utah.edu/sys/installdir/shotma
> p/1.0/ext/lib/perl5/IPC/System/Simple.pm line 566
> IPC::System::Simple::_check_exit("run_microbe_census.py -t 8
> /scratch/general/lustre/u0028729/1"..., 1, ARRAY(0x54e74d8)) called at
> /uufs/
> chpc.utah.edu/sys/installdir/shotmap/1.0/ext/lib/perl5/IPC/System/Simple.pm
> line 538
> IPC::System::Simple::_process_child_error(256, "run_microbe_census.py -t 8
> /scratch/general/lustre/u0028729/1"..., ARRAY(0x54e74d8))
> called at /uufs/
> chpc.utah.edu/sys/installdir/shotmap/1.0/ext/lib/perl5/IPC/System/Simple.pm
> line 238
> IPC::System::Simple::capture("run_microbe_census.py -t 8
> /scratch/general/lustre/u0028729/1"...) called at /uufs/
> chpc.utah.edu/sys/i
> nstalldir/shotmap/1.0/lib/Shotmap/Run.pm line 3993
> Shotmap::Run::run_microbecensus(Shotmap=HASH(0x11acf28),
> "/scratch/general/lustre/u0028729/1153141/shotmap_ffdb/n_albig"..., "/scrat
> ch/general/lustre/u0028729/1153141/shotmap_ffdb/n_albig"...,
> "/scratch/general/lustre/u0028729/1153141/shotmap_ffdb/logs/mi"...) called
> at /
> uufs/chpc.utah.edu/sys/installdir/shotmap/1.0/lib/Shotmap/Results.pm line
> 345
> Shotmap::Results::estimate_ags(Shotmap=HASH(0x11acf28)) called at /uufs/
> chpc.utah.edu/sys/installdir/shotmap/1.0/scripts/shotmap.pl
> line 77
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sharpton/shotmap/issues/7>
>



-- 
Thomas J. Sharpton

Assistant Professor
Department of Microbiology
Department of Statistics
Oregon State University

(541) 737-8623
thomas.sharpton@gmail.com
@tjsharpton
lab.sharpton.org

**Comment by amorendt** [comment]
Tom,  Thanks for the quick response.  Here is the log:

]$ more microbecensus_n_albigula_foregut_all.log
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/sys/installdir/shotmap/1.0/bin/run_microbe_census.py", line 9, in <module>
    import argparse
  File "/uufs/chpc.utah.edu/sys/installdir/xalt/2015-10-13/libexec/argparse.py", line 85, in <module>
    import copy as _copy
ImportError: No module named copy

**Comment by amorendt** [comment]
I should have added that I will look into the python modules we have installed.  Thanks,  Anita

From: Anita Orendt
Sent: Thursday, April 28, 2016 12:08 PM
To: 'sharpton/shotmap' <reply@reply.github.com>
Subject: RE: [sharpton/shotmap] Error Exit in microbecensus (#7)

Tom,  Thanks for the quick response.  Here is the log:

]$ more microbecensus_n_albigula_foregut_all.log
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/sys/installdir/shotmap/1.0/bin/run_microbe_census.py", line 9, in <module>
    import argparse
  File "/uufs/chpc.utah.edu/sys/installdir/xalt/2015-10-13/libexec/argparse.py", line 85, in <module>
    import copy as _copy
ImportError: No module named copy

**Comment by amorendt** [comment]
Tom, 

 Just wanted to let you know this issue has been resolved.  The bottom line is I needed to change the 
#!/usr/bin/python 
To
#!/usr/bin/env python

We have a separate installation of python beyond which comes with the OS.  In this case I was using  our python/2.7.3 and then the /usr/bin/python was trying the 2.6.6 that was with the OS.

Anyway, I am now getting further in the pipeline.
Thanks!

Anita

**Comment by sharpton** [comment]
Thanks for following up on this with me. I will look into potential ways to
work around such conflicts.

Best,
Tom

On Tue, May 3, 2016 at 4:15 PM, amorendt <notifications@github.com> wrote:

> Tom,
>
> Just wanted to let you know this issue has been resolved. The bottom line
> is I needed to change the
> #!/usr/bin/python
> To
> #!/usr/bin/env python
>
> We have a separate installation of python beyond which comes with the OS.
> In this case I was using our python/2.7.3 and then the /usr/bin/python was
> trying the 2.6.6 that was with the OS.
>
> Anyway, I am now getting further in the pipeline.
> Thanks!
>
> Anita
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/sharpton/shotmap/issues/7#issuecomment-216692991>
>



-- 
Thomas J. Sharpton

Assistant Professor
Department of Microbiology
Department of Statistics
Oregon State University

(541) 737-8623
thomas.sharpton@gmail.com
@tjsharpton
lab.sharpton.org
